FROM ubuntu
LABEL maintainer="Yordan - web"
RUN apt-get -qq  update
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq install -y --no-install-recommends tzdata
RUN apt-get -qq install -y software-properties-common && add-apt-repository -y ppa:ondrej/php
RUN apt-get -qq install -y php php7.4-mysql mariadb-client git nginx php7.4-fpm
RUN apt-get clean -y
COPY ngnix_cfg /etc/nginx/sites-available/default
RUN mkdir /run/php
COPY web-ngnix.sh web-ngnix.sh
RUN chmod +x web-ngnix.sh
ENTRYPOINT ["./web-ngnix.sh"]
EXPOSE 80




